apiVersion: v1
kind: Namespace
metadata:
  name: jenkins

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      containers:
        - name: jenkins
          image: tharwat3551/jenkins
          ports:
            - containerPort: 8080
            - containerPort: 50000


          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home

            - name: dockersock
              mountPath: /var/run/docker.sock
            
            - name: docker
              mountPath: /usr/bin/docker
              subPath: docker

            - name: kubernetes
              mountPath: /usr/bin/kubectl
              subPath: kubectl

          # resources:
          #   limits:
          #     cpu: 800m
          #     memory: 3Gi
          #   requests:
          #     cpu: 100m
          #     memory: 3Gi
      
      initContainers:
        - name: init-docker
          image: docker
          command: ["cp","/usr/local/bin/docker", "/opt/tmp"]
       
            
          volumeMounts:  
            - name: docker
              mountPath: /opt/tmp

        - name: init-k8s
          image: alpine/k8s:1.23.13
          command: ["cp","/usr/bin/kubectl","/opt/temp"]

          volumeMounts:
            - name: kubernetes
              mountPath: "/opt/temp"

        
      volumes:
        - name: jenkins-data
          emptyDir: {}

        - name: docker
          emptyDir: {}
        
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock

        - name: kubernetes
          emptyDir: {}
        
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  type: LoadBalancer
  selector:
    app: jenkins-server
  ports:
    - port: 8080
      targetPort: 8080  